# 📈 MCP Stock Server - MCP Registry Configuration
# Configuração para o Docker MCP Registry
# Baseado em: https://github.com/docker/mcp-registry/blob/main/CONTRIBUTING.md

name: mcp-stock-server
version: 1.0.0
description: "MCP Server para dados da bolsa de valores em tempo real"
author: "Bruno Lucena"
license: "MIT"
repository: "https://github.com/brunovlucena/mcp-stock-server"
homepage: "https://github.com/brunovlucena/mcp-stock-server"

# Metadados do servidor MCP
mcp:
  name: "stock-server"
  version: "1.0.0"
  description: "Servidor MCP para dados financeiros e da bolsa de valores"
  capabilities:
    tools: true
    resources: false
    prompts: false
    logging: true

# Configurações do Docker
docker:
  image: "mcp-stock-server"
  tag: "latest"
  platform: "linux/amd64"
  arch:
    - "amd64"
    - "arm64"
  
  # Configurações de build
  build:
    context: "."
    dockerfile: "Dockerfile"
    target: "production"
    args:
      - "NODE_ENV=production"
      - "MCP_SERVER_NAME=stock-server"
      - "MCP_SERVER_VERSION=1.0.0"
  
  # Configurações de runtime
  runtime:
    ports:
      - "3000:3000"
    environment:
      - "NODE_ENV=production"
      - "MCP_SERVER_NAME=stock-server"
      - "MCP_SERVER_VERSION=1.0.0"
      - "PORT=3000"
      - "LOG_LEVEL=info"
    volumes:
      - "./logs:/app/logs"
      - "./data:/app/data"
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check')"]
      interval: "30s"
      timeout: "10s"
      retries: 3
      start_period: "40s"

# Configurações de desenvolvimento
development:
  docker:
    image: "mcp-stock-server"
    tag: "dev"
    platform: "linux/amd64"
    build:
      context: "."
      dockerfile: "Dockerfile.dev"
      target: "development"
    runtime:
      ports:
        - "3001:3000"
      environment:
        - "NODE_ENV=development"
        - "MCP_SERVER_NAME=stock-server-dev"
        - "MCP_SERVER_VERSION=1.0.0-dev"
        - "PORT=3000"
        - "LOG_LEVEL=debug"
      volumes:
        - ".:/app"
        - "/app/node_modules"

# Configurações de teste
testing:
  docker:
    image: "mcp-stock-server"
    tag: "test"
    platform: "linux/amd64"
    build:
      context: "."
      dockerfile: "Dockerfile"
      target: "production"
    runtime:
      environment:
        - "NODE_ENV=test"
        - "MCP_SERVER_NAME=stock-server-test"
        - "MCP_SERVER_VERSION=1.0.0-test"
        - "PORT=3000"
        - "LOG_LEVEL=debug"

# Configurações de CI/CD
ci:
  build:
    context: "."
    dockerfile: "Dockerfile"
    target: "production"
    cache_from:
      - "mcp-stock-server:latest"
      - "mcp-stock-server:dev"
    cache_to:
      - "type=registry,ref=mcp-stock-server:cache"
  
  test:
    image: "mcp-stock-server:test"
    commands:
      - "npm test"
      - "npm run lint"
      - "npm run build"
  
  deploy:
    image: "mcp-stock-server:latest"
    registry: "ghcr.io"
    namespace: "brunovlucena"
    tags:
      - "latest"
      - "v1.0.0"
      - "stable"

# Configurações de monitoramento
monitoring:
  metrics:
    enabled: true
    port: 9090
    path: "/metrics"
  
  logging:
    level: "info"
    format: "json"
    output: "stdout"
  
  health:
    enabled: true
    port: 3000
    path: "/health"

# Configurações de segurança
security:
  user: "mcpuser"
  uid: 1001
  gid: 1001
  
  capabilities:
    - "NET_BIND_SERVICE"
  
  seccomp:
    profile: "default"
  
  apparmor:
    profile: "docker-default"

# Configurações de recursos
resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  
  requests:
    memory: "256Mi"
    cpu: "250m"

# Configurações de rede
network:
  mode: "bridge"
  ports:
    - "3000:3000"
  
  dns:
    - "8.8.8.8"
    - "8.8.4.4"

# Configurações de volumes
volumes:
  logs:
    type: "bind"
    source: "./logs"
    target: "/app/logs"
    mode: "rw"
  
  data:
    type: "bind"
    source: "./data"
    target: "/app/data"
    mode: "rw"

# Configurações de labels
labels:
  - "org.opencontainers.image.title=MCP Stock Server"
  - "org.opencontainers.image.description=MCP Server para dados da bolsa de valores"
  - "org.opencontainers.image.version=1.0.0"
  - "org.opencontainers.image.authors=Bruno Lucena"
  - "org.opencontainers.image.url=https://github.com/brunolucena/mcp-stock-server"
  - "org.opencontainers.image.source=https://github.com/brunolucena/mcp-stock-server"
  - "org.opencontainers.image.licenses=MIT"
  - "mcp.server.name=stock-server"
  - "mcp.server.version=1.0.0"
  - "mcp.server.capabilities=tools,logging"
